traiterJson({
	"trait":2,
	"numDiag":7,
	"notes":"Une position possible après un dual blindé.<br />Toujours un avantage pour les rouges si ils prennent leurs mals en patience, les jaunes sont légèrement en situation de Zugzwang",
	"fen":"UuUuD1uDdU2UuU r",
	"bonusJ":255,
	"malusJ":255,
	"bonusR":255,
	"malusR":255,
	"cols":[
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":2, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":2, "couleur":2},
		{"nb":2, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0}
	]
});