traiterJson({
	"trait":2,
	"numDiag":3,
	"notes":"Ici, il y a une chaine rouge de 5 pions.<br />On admet qu'il y a peu de pions jaunes voir aucun qui sont adjacents à la chaine.<br />L'objectif ici va être de séparer la chaine pour maximiser le nombre de points, notamment en jouant le coup de la case 4 à la case 0 afin de nous garantir minimum un point si il n'y a pas de pion jaune �adjacent à la case 0.",
	"fen":"U3U4U6U8U r",
	"bonusJ":255,
	"malusJ":255,
	"bonusR":255,
	"malusR":255,
	"cols":[
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0}
	]
});