traiterJson({
	"trait":2,
	"numDiag":4,
	"notes":"Une configuration très simple :<br />2 pions de la même couleurr, tous les deux adjacents au pion adverse. Nous avons alors un avantage sur la situation dans ce coin de jeu.",
	"fen":"Uu2U r",
	"bonusJ":255,
	"malusJ":255,
	"bonusR":255,
	"malusR":255,
	"cols":[
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0}
	]
});