traiterJson({
	"trait":1,
	"numDiag":4,
	"notes":"Configuration très simple , qui peut représenter n'importe quelle diagonale du jeu (à petite échelle).",
	"fen":"Uu1uUu2uUu4uU j",
	"bonusJ":255,
	"malusJ":255,
	"bonusR":255,
	"malusR":255,
	"cols":[
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0},
		{"nb":0, "couleur":0}
	]
});