traiterJson({
	"trait":2,
	"scoreJ":23,
	"scoreJ5":0,
	"scoreR":24,
	"scoreR5":0,
	"bonusJ":5,
	"malusJ":3,
	"bonusR":2,
	"malusR":4,
	"cols":[
		{"nb":1, "couleur":2},
		{"nb":0, "couleur":0},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":2, "couleur":1},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2},
		{"nb":1, "couleur":1},
		{"nb":1, "couleur":2}
	]
});